### ISSUE TITLE
Bug after generation of gds mask

### ISSUE THREAD

**Issue by tdouglas91** [INLnano/pyMOE#44] opened 2024-07-17 16:42 UTC
Sometimes I get this error halfway through .gds generation in the metalens example. It generates the fresnel_metasurface_pillars_instance.gds file but not the fresnel_metasurface_pillars.gds file and then crashes out.
![error message](https://github.com/user-attachments/assets/1fac562c-8683-41c7-8ab7-4becd3facf62)

**Comment by cunhaJ** [comment] 2024-07-17 17:41
Thank you for reporting this. Yet, I could not reproduce this issue. 

Could you please confirm that you have the required packages & versions installed as in the provided requirements file https://github.com/INLnano/pyMOE/blob/main/requirements.txt ? 

Other possible reasons, though it is hard to know from the information provided: 

1. The error reports it cannot open the `infile`, which I guess is "circle.gds", hence is the file "circle.gds" provided in same folder? Can you open "circle.gds" outside pyMOE (e.g. with KLayout) and check if is it fine (e.g. is not corrupted, etc)? 
2. Does this error appear when running the cells sequentially one after the other as they appear in the example? Because jumping across cells could cause initialization/attribution mix up.

**Comment by tdouglas91** [comment] 2024-07-18 13:55
Hi João,

I am running this in pycharm... but gdspy I have 1.6.13 (if I remember
correctly it wouldn't let me install an earlier version), klayout 0.29.2,
pillow 10.3.0, shapely 2.0.4... it wouldn't let me install zernike for some
reason... maybe that is why. But what is odd, is that sometimes it runs to
the end and sometimes it gives this error...

1. circle.gds I have in the folder "2-Metasurfaces"
2. I am running in pycharm, so I don't have the option of running cells
non-sequentially.

Temple

**Comment by cunhaJ** [comment] 2024-07-23 08:59
I don't have experience with pycharm, but it does seem very strange that you only get the error sometimes which might point to some particularities of the IDE in your system. Debugging in this particular case needs to be performed at your system/IDE, as I could not reproduce it in my end. 

Furthermore the mismatch to the recommended package versions might create trouble, and might lead some differences in outcome, but it seems to not be the case here as you report you are actually able to run without errors sometimes. 

For a smooth running experience, we recommend Jupyter Notebook or Lab with installed dependencies in the requirements.txt file. 

I am closing this issue as it seems IDE/ system dependent. If in the contrary you find that it is inherent to pyMOE please open again.

**Closed by cunhaJ** 2024-07-23 08:59 UTC
